#here you can configure snow particles
snow:
  #radius SnowFlakes will spawn around the player
  radius: 10
  #number of SnowFlakes per second
  amount: 40
  #worlds were SnowFlakes will spawn
  worlds:
    - 'world'
  #blacklist biomes where snow won't spawn
  biomes:
    - 'HELL'
    - 'DESERT'
    - 'MESA_PLATEAU_FOREST_MOUNTAINS'
    - 'MESA_PLATEAU_MOUNTAINS'
    - 'MESA_BRYCE'
    - 'MESA_PLATEAU'
  #don't spawn SnowFlakes under blocks.
  fixedspawn: true